// dvd/dts/dts_ucode.svh -- GENERATED by tools/dts_isa.py --asm; never edit.
// The sequencer's sizes and entry points, and XQ's code-reader tables
// (packed: element i at [w*i +: w]; index abits - 1).
localparam int UC_WORDS    = 521;
localparam int CONST_WORDS = 92;
localparam int HUFF_NODES  = 2647;
localparam int HUFF_BOOKS  = 62;
localparam [9:0] UC_RESET  = 10'd0;
localparam [9:0] UC_FRAME  = 10'd0;
// the first quantiser-index book of abits (book = QBOOK + selector)
localparam [59:0] XQ_QBOOK  = 60'ha626d434a1c4040;
// selectors below this are Huffman books
localparam [39:0] XQ_GSIZE  = 40'h7777733331;
// block codes (abits 1..7): bits a code, and the levels (the divisor)
localparam [34:0] XQ_BNBITS = 35'h4e2f6b147;
localparam [34:0] XQ_LEVELS = 35'h662d49ca3;
