// dvd/dts/dts_vec.svh -- GENERATED by tools/dts_isa.py --asm; never edit.
// The vector engine's ROM sizes and the constant ROM's bases (tools/dts_vecrom.py).
localparam int VK_WORDS    = 512;
localparam [8:0] VK_SCALE6 = 9'd0;
localparam [8:0] VK_SCALE7 = 9'd64;
localparam [8:0] VK_STEP   = 9'd192;
localparam [8:0] VK_JOINT  = 9'd256;
localparam [8:0] VK_ADJ    = 9'd385;
localparam [8:0] VK_GAIN   = 9'd389;
localparam int IPROG_WORDS = 597;
localparam int ICOEF_WORDS = 113;
// primary channels by AMODE (packed: element i at [3*i +: 3])
localparam [29:0] VK_NCH = 30'h2c8da491;
