// dvd/dts/dts_cb.svh -- GENERATED by tools/dts_isa.py --asm; never edit.
// The DTS codebooks' checksum as dvd/dts/dts_cb_mem.sv computes it over the
// copy (docs/dts_decoder.md D4): a mismatch leaves tables_ok low.
localparam [31:0] CB_SUM = 32'h6e6f7b8d;
