// dvd/dts/dts_ucode.svh -- GENERATED by tools/dts_isa.py --asm; never edit.
// The engine's sizes, both programs' entry points (DTS at 0, AC-3 after it, in
// one ROM), and XQ's code-reader tables (packed: element i at [w*i +: w];
// index abits - 1).
localparam int UC_WORDS    = 1279;
localparam int CONST_WORDS = 784;
localparam int HUFF_NODES  = 2647;
localparam int HUFF_BOOKS  = 62;
localparam [10:0] UC_DTS_RESET = 11'd0;
localparam [10:0] UC_DTS_FRAME = 11'd0;
localparam [10:0] UC_AC3_RESET = 11'd500;
localparam [10:0] UC_AC3_FRAME = 11'd500;
localparam [5:0]  UC_ERRV      = 6'd63;      // error vectors: pc[10:5] == this
// the first quantiser-index book of abits (book = QBOOK + selector)
localparam [59:0] XQ_QBOOK  = 60'ha626d434a1c4040;
// selectors below this are Huffman books
localparam [39:0] XQ_GSIZE  = 40'h7777733331;
// block codes (abits 1..7): bits a code, and the levels (the divisor)
localparam [34:0] XQ_BNBITS = 35'h4e2f6b147;
localparam [34:0] XQ_LEVELS = 35'h662d49ca3;
