// dvd/dts/dts_ucode.svh -- GENERATED by tools/dts_isa.py --asm; never edit.
// The engine's sizes, both programs' entry points (DTS at 0, AC-3 after it, in
// one ROM), and XQ's code-reader tables (packed: element i at [w*i +: w];
// index abits - 1).
localparam int UC_WORDS    = 1549;
localparam int CONST_WORDS = 997;
localparam int HUFF_NODES  = 2647;
localparam int HUFF_BOOKS  = 62;
localparam [10:0] UC_DTS_RESET = 11'd0;
localparam [10:0] UC_DTS_FRAME = 11'd1;
localparam [10:0] UC_AC3_RESET = 11'd501;
localparam [10:0] UC_AC3_FRAME = 11'd501;
localparam [5:0]  UC_ERRV      = 6'd63;      // error vectors: pc[10:5] == this
// the first quantiser-index book of abits (book = QBOOK + selector)
localparam [59:0] XQ_QBOOK  = 60'ha626d434a1c4040;
// selectors below this are Huffman books
localparam [39:0] XQ_GSIZE  = 40'h7777733331;
// block codes (abits 1..7): bits a code, and the levels (the divisor)
localparam [34:0] XQ_BNBITS = 35'h4e2f6b147;
localparam [34:0] XQ_LEVELS = 35'h662d49ca3;
// AC-3 (docs/ac3_engine.md A2): the units' constant-ROM tables (word offsets),
// record words, op numbers and refusal codes
localparam [9:0]  AC_LATAB   = 10'd521;
localparam [9:0]  AC_BAPTAB  = 10'd216;
localparam [9:0]  AC_MLEV    = 10'd784;       // + 0 / 3 / 8 / 16 / 27
localparam [10:0] AC_CPLBASE = 11'd1499;
localparam [10:0] AC_F_PSD   = 11'd25;
localparam [4:0]  AC_E_EXP   = 5'd9;
localparam [4:0]  AC_E_GROUP = 5'd10;
localparam [5:0]  V_EXPD    = 6'd16;
localparam [5:0]  V_BAPSD   = 6'd17;
localparam [5:0]  V_BAPFILL = 6'd18;
localparam [5:0]  V_BAPZERO = 6'd19;
localparam [5:0]  V_QRST    = 6'd20;
localparam [5:0]  V_AQ      = 6'd21;
localparam [5:0]  V_AQC     = 6'd22;
localparam [5:0]  V_CZERO   = 6'd23;
localparam [5:0]  V_REMAT   = 6'd24;
localparam [5:0]  V_IMDCT   = 6'd25;
// MP2 (docs/mp2_engine.md): the entry points, its words in icoef, the op numbers
localparam [10:0] UC_MP2_RESET = 11'd1309;
localparam [10:0] UC_MP2_FRAME = 11'd1310;
localparam [7:0]  MP2_IC_C     = 8'd128;
localparam [7:0]  MP2_IC_SCF   = 8'd160;
localparam [5:0]  V_MDQ     = 6'd26;
localparam [5:0]  V_MSYN    = 6'd27;
localparam [5:0]  V_RCLR    = 6'd28;
localparam [5:0]  V_MFS     = 6'd29;
